name: Build and Upload Artifacts

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x64
          - os: macos-15
            arch: arm64
          - os: macos-15
            arch: x64
          - os: windows-2025
            arch: x64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rosetta for macOS
        if: runner.os == 'macOS'
        run: |
          sudo softwareupdate --install-rosetta --agree-to-license

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: ${{ matrix.arch }}

      - name: Make build scripts executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x buildtools/build_macos.sh buildtools/build_linux.sh

      - name: Run build script on Windows
        if: runner.os == 'Windows'
        run: buildtools\build_win.cmd # -> buildtools\lanlogin.exe

      - name: Run build script on macOS arm64
        if: runner.os == 'macOS' && matrix.arch == 'arm64'
        run: ./buildtools/build_macos.sh # -> buildtools/lanlogin

      - name: Run build script on macOS x64
        if: runner.os == 'macOS' && matrix.arch == 'x64'
        run: arch -x86_64 ./buildtools/build_macos.sh # -> buildtools/lanlogin

      - name: Run build script on Linux
        if: runner.os == 'Linux'
        run: ./buildtools/build_linux.sh # -> buildtools/lanlogin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lanlogin-${{ runner.os }}-${{ matrix.arch }}
          path: buildtools/lanlogin*

  create-universal-binary:
    needs: build
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: lanlogin-macOS-arm64
          path: buildtools/arm64

      - name: Download x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: lanlogin-macOS-x64
          path: buildtools/x64

      - name: Create Universal Binary
        run: |
          lipo -create buildtools/arm64/lanlogin buildtools/x64/lanlogin -output buildtools/lanlogin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lanlogin-macOS-universal
          path: buildtools/lanlogin
