name: Build and Upload Artifacts

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [
            ubuntu-24.04,
            macos-15, # arm64
            macos-15-large, # x86_64
            windows-2025,
          ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Make build scripts executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x buildtools/build_macos.sh buildtools/build_linux.sh

      - name: Run build script on Windows
        if: runner.os == 'Windows'
        run: buildtools\build_win.cmd # -> buildtools\lanlogin.exe

      - name: Run build script on macOS
        if: runner.os == 'macOS'
        run: ./buildtools/build_macos.sh # -> buildtools/lanlogin, both arm64 and x86_64

      - name: Run build script on Linux
        if: runner.os == 'Linux'
        run: ./buildtools/build_linux.sh # -> buildtools/lanlogin

      - name: Set artifact name
        # lanlogin-{runner.os}-{arm64/x64}
        shell: bash
        run: |
          if [[ ${{ runner.os }} == 'macOS' ]]; then
            if [[ ${{ matrix.os }} == 'macos-15' ]]; then
              echo "ARTIFACT_NAME=lanlogin-macOS-arm64" >> $GITHUB_ENV
            else
              echo "ARTIFACT_NAME=lanlogin-macOS-x64" >> $GITHUB_ENV
            fi
          else
            echo "ARTIFACT_NAME=lanlogin-${{ runner.os }}-x64" >> $GITHUB_ENV
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: buildtools/lanlogin*

  create-universal-binary:
    needs: build
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: lanlogin-macOS-arm64
          path: buildtools/arm64

      - name: Download x86_64 artifact
        uses: actions/download-artifact@v4
        with:
          name: lanlogin-macOS-x64
          path: buildtools/x64

      - name: Create Universal Binary
        run: |
          lipo -create buildtools/arm64/lanlogin buildtools/x64/lanlogin -output buildtools/lanlogin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lanlogin-macOS-universal
          path: buildtools/lanlogin
